Handle failures better.

diff --git a/drunner/servicerunner b/drunner/servicerunner
--- a/drunner/servicerunner
+++ b/drunner/servicerunner
@@ -86,6 +86,7 @@ function build_low {
       echo "Building ${BASEIMAGENAME} from branch ${BRANCH}"
    fi
    docker build -t "${BASEIMAGENAME}" . && saygood "Built ${BASEIMAGENAME}"
+   [ $? -eq 0 ] || die "Build failed."
 
    [ "$DSERVICE" = "yes" ] || { sayinfo "Not a dService, so we're all done."; return 0; }
    [ -n "$DEVSERVICENAME" ] || { sayinfo "DEVSERVICENAME not defined, not attempting to install."; return 0; }
@@ -93,6 +94,7 @@ function build_low {
 
    sayinfo "Installing as ${DEVSERVICENAME}"
    drunner -d -v recover "$DEVSERVICENAME" "$BASEIMAGENAME"
+   [ $? -eq 0 ] || die "dService installation failed."
    drunner status "$DEVSERVICENAME"
    saygood "dService $DEVSERVICENAME updated from just built $BASEIMAGENAME (branch ${BRANCH})"
 }
