Tidy up - don't need any containers!

diff --git a/drunner/servicerunner b/drunner/servicerunner
--- a/drunner/servicerunner
+++ b/drunner/servicerunner
@@ -28,15 +28,20 @@ NAME
    ${SERVICENAME}
 
 SYNOPSIS
-   ${SERVICENAME} [-a] build
-   ${SERVICENAME} [-a] info
-   ${SERVICENAME} [-a] check
-   ${SERVICENAME} [-a] test
+   ${SERVICENAME} build
+   ${SERVICENAME} info
+   ${SERVICENAME} check
+   ${SERVICENAME} test
 
-   ${SERVICENAME} configure
+   ${SERVICENAME} buildall
+   ${SERVICENAME} infoall
+   ${SERVICENAME} checkall
+   ${SERVICENAME} testall
+
+   ${SERVICENAME} configure [DEVPATH]
 
 DESCRIPTION
-   A simple dRunner container from ${IMAGENAME} (${INSTALLTIME})
+   A simple dRunner container from ${IMAGENAME}
 
 EOF
 }
@@ -46,13 +51,6 @@ EOF
 function sayinfo { echo -e "] \e[2m${1}\e[0m" ; }
 function saygood { echo -e "] \e[32m${1}\e[0m" ; }
 function saybad { echo -e "] \e[31m\e[1m${1}\e[0m" ; }
-
-function dockerrun {
-   local RVAL=0
-   docker run -i --name="${SERVICENAME}-${COMMAND}" -h "${HOSTNAME}" "${DOCKEROPTS[@]}" "${IMAGENAME}" "$@" || RVAL=$?
-   docker rm "${SERVICENAME}-${COMMAND}" >/dev/null
-   if [ $RVAL -ne 0 ]; then die "${SERVICENAME} ${COMMAND} failed." ; fi
-}
 
 function isrepo {
    (
@@ -67,6 +65,8 @@ function isdev {
 }
 
 
+#---------------------------------------------------------------------------------
+
 function info_low {
    sayinfo "DSERVICE:       $DSERVICE"
    sayinfo "BUILDNAME:      $BUILDNAME"
@@ -75,7 +75,6 @@ function info_low {
    sayinfo "DIRECTORY:      $1"
    return 0
 }
-
 
 #---------------------------------------------------------------------------------
 
@@ -100,16 +99,21 @@ function build_low {
    fi
 }
 
+#---------------------------------------------------------------------------------
 
 function check_low {
    [ "$DSERVICE" = "yes" ] || { sayinfo "$1 - skipping non-dService $BRANCHEDIMAGENAME." ; return 1 ; }
    drunner checkimage "$BRANCHEDIMAGENAME" && saygood "$BRANCHEDIMAGENAME is valid."
 }
 
+#---------------------------------------------------------------------------------
+
 function test_low {
    [ "$DSERVICE" = "yes" ] || { sayinfo "$1 - skipping non-dService $BRANCHEDIMAGENAME." ; return 0 ; }
    dtest test "$BRANCHEDIMAGENAME"
 }
+
+#---------------------------------------------------------------------------------
 
 function title {
    echo " ">&2
@@ -143,7 +147,13 @@ function run1cmd {
 }
 
 function runcmd {
-   [ -v DEVPATH ] || { run1cmd "$1" "$PWD" ; return $? ; }
+   run1cmd "$1" "$PWD" ; return $? ;
+}
+
+function runcmdall {
+   [[ -v DEVPATH ]] || die "${SERVICENAME} configure first."
+
+   # run on devpath
    local TESTSOK=0
    local TOTALIMGS=0
    (
@@ -167,12 +177,6 @@ function main {
    [ "$#" -gt 0 ] || { showhelp ; exit 1 ; }
    COMMAND="${1}" ; shift
 
-   if [ "$COMMAND" = "-a" ]; then
-      DEVPATH=$(dockerrun cat /config/path) || die "Call ${SERVICENAME} configure first."
-      [ "$#" -gt 0 ] || { showhelp ; exit 1 ; }
-      COMMAND="${1}" ; shift
-   fi
-
    case "$COMMAND" in
 
           #--- standard (required) commands
@@ -182,7 +186,7 @@ function main {
             ;;
 
          enter)
-            dockerrun /bin/bash "$@"
+            die "enter not supported for ddev."
             ;;
 
          selftest)
@@ -206,30 +210,48 @@ function main {
             runcmd test_low
             ;;
 
+         buildall)
+            runcmdall build_low
+            ;;
+
+         infoall)
+            runcmdall info_low
+            ;;
+
+         checkall)
+            runcmdall check_low
+            ;;
+
+         testall)
+            runcmdall test_low
+            ;;
+
          configure)
-            dockerrun bash -c "echo $PWD > /config/path"
-            DEVPATH=$(dockerrun cat /config/path) || die "Configure failed."
+            DEVPATH="$PWD"
+            [ $# -eq 0 ] || DEVPATH="$1"
+
+            save_environment "DEVPATH" "${DEVPATH}"
             echo "Path set to $DEVPATH"
             ;;
 
-         clone)
-            [ -v DEVPATH ] || die "Clone requires -a flag."
-            local PROJECTS=("samba" "dtest" "ddev")
-            PROJECTS+=("simplesecrets" "minecraft" "helloworld")
-            for PROJECT in "${PROJECTS[@]}"; do
-               (
-               cd "${DEVPATH}"
-               if [ ! -e "$PROJECT" ]; then
-                  (
-                  git clone "https://github.com/drunner/${PROJECT}.git" || die "Failed to clone $PROJECT"
-                  cd ${PROJECT}
-                  git checkout dev
-                  )
-                  [ $? -eq 0 ] || die "Failed to set up $PROJECT."
-               fi
-               )
-            done
-            ;;
+         # clone)
+         #    [ -v DEVPATH ] || die "Clone requires -a flag."
+         #    local PROJECTS=("samba" "dtest" "ddev")
+         #    PROJECTS+=("simplesecrets" "minecraft" "helloworld")
+         #    for PROJECT in "${PROJECTS[@]}"; do
+         #       (
+         #       cd "${DEVPATH}"
+         #       if [ ! -e "$PROJECT" ]; then
+         #          (
+         #          git clone "https://github.com/drunner/${PROJECT}.git" || die "Failed to clone $PROJECT"
+         #          cd ${PROJECT}
+         #          git checkout dev
+         #          )
+         #          [ $? -eq 0 ] || die "Failed to set up $PROJECT."
+         #       fi
+         #       )
+         #    done
+         #    ;;
 
          #--- unrecognised commands
 
